import json
from typing import Any, Iterable


def toml_quote(value: Any) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def default_remap(name: str) -> str:
    return {
        "touchpad_left": "dpad_left",
        "touchpad_right": "dpad_right",
    }.get(name, "passthrough")


def serialize_config(config: dict[str, Any], source_buttons: Iterable[str]) -> str:
    lines = ["# Generated by edgemap config editor", "version = 2"]
    output_device = config.get("output_device", "auto")
    if output_device != "auto":
        lines.append(f"output_device = {toml_quote(output_device)}")
    lines.append("")

    for name in source_buttons:
        if name in ("touchpad_left", "touchpad_right"):
            touchpad = config.get("touchpad", {})
            if touchpad.get("remap", "") != "split":
                continue
        button = config.get(name, {})
        remap = button.get("remap", default_remap(name)) or default_remap(name)
        lines.append(f"[{name}]")
        if remap:
            lines.append(f"remap = {toml_quote(remap)}")
        if button.get("turbo"):
            lines.append("turbo = true")
            interval = button.get("turbo_interval_ms", 100)
            if interval != 100:
                lines.append(f"turbo_interval_ms = {interval}")
            delay = button.get("turbo_delay_ms", 0)
            if delay:
                lines.append(f"turbo_delay_ms = {delay}")
        for combo in button.get("combos", []):
            lines.append(f"[[{name}.combos]]")
            lines.append(f"key = {toml_quote(combo.get('key', ''))}")
            lines.append(f"output = {toml_quote(combo.get('output', ''))}")
        lines.append("")

    for macro_name, macro in config.get("macros", {}).items():
        lines.append(f"[macros.{toml_quote(macro_name)}]")
        lines.append(f"mode = {toml_quote(macro.get('mode', 'hold'))}")
        for step in macro.get("sequence", []):
            lines.append(f"[[macros.{toml_quote(macro_name)}.sequence]]")
            lines.append(f"key = {toml_quote(step.get('key', ''))}")
            lines.append(f"press_ms = {step.get('press_ms', 0)}")
            lines.append(f"release_ms = {step.get('release_ms', 0)}")
        lines.append("")
    return "\n".join(lines) + "\n"


def serialize_profiles(data: dict[str, Any]) -> str:
    lines = [f"config = {toml_quote(data.get('config', 'default.toml'))}"]
    profiles = data.get("profiles", {})
    if profiles:
        lines.append("")
    for name, profile in profiles.items():
        lines.append(f"[profiles.{name}]")
        lines.append(f"config = {toml_quote(profile.get('config', 'default.toml'))}")
        if profile.get("match_process"):
            lines.append(f"match_process = {toml_quote(profile['match_process'])}")
        if profile.get("match_cmdline"):
            lines.append(f"match_cmdline = {toml_quote(profile['match_cmdline'])}")
        lines.append("")
    return "\n".join(lines) + "\n"
