name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: cargo build --release

      - name: Package tarball
        run: |
          TAG=${GITHUB_REF_NAME}
          DIR="edgemap-${TAG}-x86_64"
          mkdir -p "${DIR}/usr/lib/systemd/system"
          mkdir -p "${DIR}/usr/lib/systemd/user"
          mkdir -p "${DIR}/usr/local/lib/edgemap-gui"
          mkdir -p "${DIR}/usr/share/applications"
          mkdir -p "${DIR}/usr/share/icons/hicolor/scalable/apps"
          mkdir -p "${DIR}/usr/share/zsh/site-functions"

          cp target/release/dseuhid "${DIR}/"
          cp target/release/edgemap "${DIR}/"
          cp gui/edgemap-gui "${DIR}/edgemap-gui"
          cp install.sh "${DIR}/"

          while IFS= read -r source; do
            relative=${source#gui/}
            install -Dm644 "${source}" "${DIR}/usr/local/lib/edgemap-gui/${relative}"
          done < <(find gui/edgemap_gui -type f -name '*.py' | sort)

          sed 's|/usr/bin/|/usr/local/bin/|g' dseuhid.service > "${DIR}/usr/lib/systemd/system/dseuhid.service"
          sed 's|/usr/bin/|/usr/local/bin/|g' edgemap.service > "${DIR}/usr/lib/systemd/user/edgemap.service"

          cp edgemap.svg "${DIR}/usr/share/icons/hicolor/scalable/apps/"
          cp edgemap.desktop "${DIR}/usr/share/applications/"
          cp completions/_dseuhid "${DIR}/usr/share/zsh/site-functions/"
          cp completions/_edgemap "${DIR}/usr/share/zsh/site-functions/"

          tar -czf "${DIR}.tar.gz" "${DIR}/"

      - uses: softprops/action-gh-release@v2
        with:
          files: edgemap-*.tar.gz
